### ISSUE TITLE
2 requirements are fixed on too old version

### ISSUE THREAD

**Issue by Lostsite** [federicotorrielli/BetterWhisperX#4]
`/pyannote/audio/core/inference.py` line 533, use `np.NaN` instead `np.nan`

`/pyannote/audio/pipelines/speaker_diarization.py` line 404 use `np.NAN` instead `np.nan`

Both of them should be already corrected in newer releases, but I think pyannote had been fixed somewhere in the requirements, so, if you can update it, it would be great!

**Comment by federicotorrielli** [comment]
I updated the pyannote and the ctranslate2 version, please close the issue if it has been resolved
