### ISSUE TITLE
Kernel crash / Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}

### ISSUE THREAD

**Issue by dwidoo** [federicotorrielli/BetterWhisperX#5]
I hadn't any issue a few days ago. 
The same code crashes today. 

Here is the log : 

> <head></head>
Timestamp | Level | Message
-- | -- | --
Dec 6, 2024, 4:31:41 PM | WARNING | WARNING:root:kernel e6312b98-133a-476f-9b78-8e3b6c02c912 restarted
Dec 6, 2024, 4:31:41 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Dec 6, 2024, 4:31:39 PM | WARNING | Invalid handle. Cannot load symbol cudnnCreateConvolutionDescriptor
Dec 6, 2024, 4:31:39 PM | WARNING | Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}

**Comment by federicotorrielli** [comment]
Please read the warning in the README.md:
```
The ctranslate2 version was updated to 4.5.0, which is not compatible with cuda and cudnn 8.x. If you are using a GOOGLE COLAB GPU, please install ctranslate2 4.4.0. In any other case, please install the latest cuda and cudnn versions on your environment.
```

**Comment by dwidoo** [comment]
My mistake.
Thank you Federico

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Federico Torrielli ***@***.***>
Envoyé : Saturday, December 7, 2024 11:40:31 AM
À : federicotorrielli/BetterWhisperX ***@***.***>
Cc : dwidoo ***@***.***>; Author ***@***.***>
Objet : Re: [federicotorrielli/BetterWhisperX] Kernel crash / Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so} (Issue #5)


Please read the warning in the README.md:

The ctranslate2 version was updated to 4.5.0, which is not compatible with cuda and cudnn 8.x. If you are using a GOOGLE COLAB GPU, please install ctranslate2 4.4.0. In any other case, please install the latest cuda and cudnn versions on your environment.
